version: "3.5"
services:
  qbittorrent:
    image: qiyuey/qbittorrentee
    container_name: qbittorrentee
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Shanghai
    volumes:
      - /Users/yuchuan/Code/Docker/config:/config
      - /Users/yuchuan/Code/Docker/downloads:/downloads
      - /Users/yuchuan/Code/Docker/cert:/cert
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 6363:6363
    restart: unless-stopped
